name: audiolearn
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 2.4.3

environment:
  sdk: '>=3.3.4 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size  
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  audioplayers: ^6.6.0
  provider: ^6.1.5
  youtube_explode_dart: ^3.0.5
  http: ^1.4.0 # fixed audio download difficulties
  googleapis: ^16.0.0
  googleapis_auth: ^2.0.0
  audio_video_progress_bar: ^2.0.0
  rxdart: ^0.28.0
  another_flushbar: ^2.0.1
  url_launcher: ^6.3.2
  path: ^1.9.1
  permission_handler: ^12.0.1
  window_manager: ^0.5.1
  collection: ^1.19.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  
  connectivity_plus: ^7.0.0
  file_picker: ^10.3.10 
  matcher: ^0.12.16+1
  yaml: ^3.1.2
  archive: ^4.0.2
  app_settings: ^7.0.0
  volume_controller: ^3.4.0
  logger: ^2.6.2
  path_provider: ^2.1.5
  ffmpeg_kit_flutter_new: ^4.1.0
  flutter_tts: ^4.2.5
  dtd: ^4.0.0
  flutter_lints: ^6.0.0
  google_fonts: ^8.0.0
  json_rpc_2: ^4.0.0
  stack_trace: ^1.12.1
  web: ^1.1.1
  code_builder: ^4.11.1
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  intl_utils: ^2.0.0
  mockito: ^5.4.4
  build_runner: ^2.3.3
  msix: ^3.16.13

msix_config:
  display_name: AudioLearn
  publisher_display_name: Jean-Pierre Schnyder
  identity_name: com.schnyder.audiolearn     # use a real reverse-domain name
  msix_version: 3.3.4.0                      # match your app version
  logo_path: assets\icons\audiolearn.ico
  capabilities: microphone, internetClient
  languages: en, fr                          # add French since your app is bilingual

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  generate: true
  assets:
    - lib/l10n/
    - assets\icons\audiolearn.ico
    - assets/images/
    - assets/audio/
    - assets/help/french/playlist_usage/help_content.json
    - assets/help/french/playlist_usage/images/
    - assets/help/french/playlist_local_usage/help_content.json
    - assets/help/french/playlist_local_usage/images/
    - assets/help/french/text_to_speech_conversion/help_content.json
    - assets/help/french/text_to_speech_conversion/images/
